#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    component-skeleton-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^component-skeleton\.ddev\.site$`)
      
      service: "component-skeleton-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "component-skeleton-redirectHttps"
    component-skeleton-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^component-skeleton\.ddev\.site$`)
      
      service: "component-skeleton-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "component-skeleton-redirectHttps"
    
    
    
    component-skeleton-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^component-skeleton\.ddev\.site$`)
      
      service: "component-skeleton-web-80"
      ruleSyntax: v3
      
      tls: true
      
    component-skeleton-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^component-skeleton\.ddev\.site$`)
      
      service: "component-skeleton-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    component-skeleton-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    component-skeleton-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-component-skeleton-web:80
        
    component-skeleton-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-component-skeleton-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/component-skeleton.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/component-skeleton.key